export const wizardDom = {
  step1El: document.getElementById("step1"),
  step2El: document.getElementById("step2"),
  countOptions: document.getElementById("countOptions"),
  quickSelect: document.getElementById("quickSelect"),
  bulkFlags: document.getElementById("bulkFlags"),
  clientGrid: document.getElementById("clientGrid"),
  wizardSummary: document.getElementById("wizardSummary"),
  wizardEditorBackdrop: document.getElementById("wizardEditorBackdrop"),
  wizardEditorPanel: document.getElementById("wizardEditorPanel"),
  wizardEditorEyebrow: document.getElementById("wizardEditorEyebrow"),
  wizardEditorTitle: document.getElementById("wizardEditorTitle"),
  wizardEditorBody: document.getElementById("wizardEditorBody"),
  wizardEditorCloseBtn: document.getElementById("wizardEditorCloseBtn"),
  cwdInput: document.getElementById("cwdInput"),
  cwdBrowseBtn: document.getElementById("cwdBrowseBtn"),
  backBtn: document.getElementById("backBtn"),
  launchBtn: document.getElementById("launchBtn"),
  savePresetBtn: document.getElementById("savePresetBtn"),
  presetSection: document.getElementById("presetSection"),
  presetList: document.getElementById("presetList"),
  savedSectionEmpty: document.getElementById("savedSectionEmpty"),
  savedSection: document.getElementById("savedSection"),
  sessionSection: document.getElementById("sessionSection"),
  sessionList: document.getElementById("sessionList")
};
